/opt/taikyoku_shogi/data/run/*.log
/opt/taikyoku_shogi/data/raw/tourney/*/analysis/*.log {
    size 50M
    rotate 4
    compress
    delaycompress
    copytruncate
    missingok
    notifempty
    su root root
}
